services:
  - name: la-min-paing-bot
    type: web
    env: python
    branch: main
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python la_min_paing_bot.py
    envVars:
      OPENAI_API_KEY: ""
      TELEGRAM_BOT_TOKEN: ""
